name = "fynth"
version = "0.1.0"
license = "BSD 3-Clause"
author = "Jeff Irwin"

description = "fynth is a synthesizer and audio processor"
categories = ["synthesizer", "audio", "music"]
homepage = "https://github.com/jeffirwin/fynth"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
#module-naming = false
module-naming = true

[install]
library = true
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

