
name: ci

on: [push]

jobs:

  test-docker:

    name: Test in docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test in docker
      run: |
        docker build . -t rocky

