
name: ci

on: [push]

jobs:

  test-docker:
    name: Test in docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test in docker
      run: |
        docker build . -t rocky

  test-matrix:
    name: Test ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          #- {compiler: lfortran, version: '0.51.0'}

        # ifx complains on windows ci/cd:
        #
        #     link: unknown option -- d
        #
        # setvars.bat is being called and warns about being called twice. ifx is
        # fine locally, not sure what the issue is.  --verbose provides no more
        # info, it's some bad backend linking step
        include:
          - os: ubuntu-latest
            toolchain: {compiler: intel, version: "2025.1"}

        #include:
        #  - os: ubuntu-latest
        #    # nvidia compiles but fails every md5 test and then segfaults
        #    # might be due to non-standard integer overflow behavior
        #    toolchain: {compiler: nvidia-hpc, version: '25.1'}

    steps:
    - uses: actions/checkout@v3
    - uses: fortran-lang/setup-fpm@v7
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
    - name: Test fynth on ${{ matrix.os }}
      run: |
        fpm test

