
name: ci

on: [push]

jobs:

  test-docker:
    name: Test in docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test in docker
      run: |
        docker build . -t rocky

  test-matrix:
    name: Test ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }} on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: "2024.1"}
          #- {compiler: lfortran, version: '0.51.0'}

        #include:
        #  - os: ubuntu-latest
        #    # nvidia compiles but fails every md5 test and then segfaults
        #    # might be due to non-standard integer overflow behavior
        #    toolchain: {compiler: nvidia-hpc, version: '25.1'}

    steps:
    - uses: actions/checkout@v3
    - uses: fortran-lang/setup-fpm@v7
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
    - name: Activate oneAPI
      if: matrix.os == 'windows-latest' && matrix.toolchain.compiler == 'intel'
      shell: cmd
      run: |
        call "%ONEAPI_ROOT%\setvars.bat"
        set | findstr /c:"oneAPI" >> "%GITHUB_ENV%"

    - name: Test fynth on ${{ matrix.os }}
      env:
        FPM_FC: "${{ env.FC }}"
      shell: cmd
      run: |
        fpm test --verbose --compiler "$FPM_FC"

